### ISSUE TITLE
Error when transcoding MKV: TypeError: '>=' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by garymm** [pannal/plex-for-kodi#23]
I see this error when trying to play an MPEG-2 video on my Vero 4k running Kodi 19.

Seems like the problem may be that `obj.startOffset` might be None and that's not handled?

https://github.com/pannal/plex-for-kodi/blob/f10eb84/lib/_included_packages/plexnet/plexplayer.py#L449

Log excerpt below:

```
2021-08-22 16:07:03.242 T:3649     INFO <general>: script.plex: API: Choice media: 480, 6.5 Mbps container=mkv videoCodec=mpeg2video audioCodec=ac3 audioChannels=6 id=2810 part:0
2021-08-22 16:07:03.243 T:3649     INFO <general>: script.plex: API: Choice videoStream: <plexnet.plexstream.PlexStream object at 0xea5dc7d0>
2021-08-22 16:07:03.243 T:3649     INFO <general>: script.plex: API: Choice audioStream: <plexnet.plexstream.PlexStream object at 0xd7c424d0>
2021-08-22 16:07:03.243 T:3649     INFO <general>: script.plex: API: Choice subtitleStream: <plexnet.plexstream.PlexStream object at 0xd7c42570>
2021-08-22 16:07:03.243 T:3649    DEBUG <CSettingsManager>: requested setting (local_mediaId) was not found.
2021-08-22 16:07:03.243 T:3649    DEBUG <CSettingsManager>: requested setting (allow_4k) was not found.
2021-08-22 16:07:03.244 T:3649    DEBUG <CSettingsManager>: requested setting (local_quality) was not found.
2021-08-22 16:07:03.244 T:3649    DEBUG <CSettingsManager>: Skipped 1 duplicate messages..
2021-08-22 16:07:03.244 T:3649    DEBUG <CSettingsManager>: requested setting (burn_subtitles) was not found.
2021-08-22 16:07:03.244 T:3649    DEBUG <CSettingsManager>: requested setting (allow_4k) was not found.
2021-08-22 16:07:03.244 T:3649    DEBUG <CSettingsManager>: requested setting (local_quality) was not found.
2021-08-22 16:07:03.247 T:3649     INFO <general>: Skipped 1 duplicate messages..
2021-08-22 16:07:03.247 T:3649     INFO <general>: script.plex: API: MDE: MediaChoice: direct playable=True version=480, 6.5 Mbps container=mkv videoCodec=mpeg2video audioCodec=ac3 audioChannels=6 id=2810
2021-08-22 16:07:03.247 T:3649    DEBUG <CSettingsManager>: requested setting (playback_directplay) was not found.
2021-08-22 16:07:03.248 T:3649    DEBUG <CSettingsManager>: requested setting (playback_remux) was not found.
2021-08-22 16:07:03.250 T:3677    DEBUG <general>: ffmpeg[0xb0a294e0X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2021-08-22 16:07:03.251 T:3649     INFO <general>: script.plex: API: Forced Transcode; allowDirectStream=False
2021-08-22 16:07:03.252 T:3649     INFO <general>: script.plex: API: DEBUG: buildDirectPlay()
2021-08-22 16:07:03.254 T:3649     INFO <general>: script.plex: API: Choice media: 480, 6.5 Mbps container=mkv videoCodec=mpeg2video audioCodec=ac3 audioChannels=6 id=2810 part:1
2021-08-22 16:07:03.255 T:3649     INFO <general>: script.plex: API: Choice videoStream: <plexnet.plexstream.PlexStream object at 0xd7c421b0>
2021-08-22 16:07:03.255 T:3649     INFO <general>: script.plex: API: Choice audioStream: <plexnet.plexstream.PlexStream object at 0xd7c427d0>
2021-08-22 16:07:03.255 T:3649     INFO <general>: script.plex: API: Choice subtitleStream: <plexnet.plexstream.PlexStream object at 0xd7c42690>
2021-08-22 16:07:03.255 T:3649    DEBUG <CSettingsManager>: requested setting (local_mediaId) was not found.
2021-08-22 16:07:03.255 T:3649    DEBUG <CSettingsManager>: requested setting (allow_4k) was not found.
2021-08-22 16:07:03.255 T:3649    DEBUG <CSettingsManager>: requested setting (local_quality) was not found.
2021-08-22 16:07:03.256 T:3649    DEBUG <CSettingsManager>: Skipped 1 duplicate messages..
2021-08-22 16:07:03.256 T:3649    DEBUG <CSettingsManager>: requested setting (burn_subtitles) was not found.
2021-08-22 16:07:03.256 T:3649    DEBUG <CSettingsManager>: requested setting (allow_4k) was not found.
2021-08-22 16:07:03.256 T:3649    DEBUG <CSettingsManager>: requested setting (local_quality) was not found.
2021-08-22 16:07:03.258 T:3649     INFO <general>: Skipped 1 duplicate messages..
2021-08-22 16:07:03.258 T:3649     INFO <general>: script.plex: API: DEBUG: buildDirectPlay()
2021-08-22 16:07:03.259 T:3649     INFO <general>: script.plex: API: Constructed video item for playback: {'duration': 12827748, 'fullHD': False, 'streamQualities': ['SD'], 'frameRate': 30, 'subtitleConfig': {'TrackName': 'mkv/3'}, 'live': False, 'partIndex': 0, 'startOffset': 0, 'partDuration': 7359886, 'isRequestToServer': True, 'streamUrls': ['https://192-168-88-127.5e73541c3cac41bb82538ac30eae5baf.plex.direct:32400/library/parts/2967/1614924057/file.mkv?X-Plex-Token=rs2zYmc2AssZ-FwWziQp'], 'token': 'rs2zYmc2AssZ-FwWziQp', 'streamFormat': 'mkv', 'streamBitrates': [6450], 'isTranscoded': False, 'audioLanguageSelected': 'hin', 'prevObj': None, 'nextPart': <AttributeDict:None:b'None'>, 'playStart': 0}
2021-08-22 16:07:03.259 T:3649     INFO <general>: script.plex: API: DEBUG: buildTranscode()
2021-08-22 16:07:03.260 T:3649     INFO <general>: script.plex: API: DEBUG: buildTranscodeMkv()
2021-08-22 16:07:03.267 T:3649    ERROR <general>: _________________________________________________________________________________
2021-08-22 16:07:03.267 T:3649    ERROR <general>: script.plex: ERROR:
2021-08-22 16:07:03.267 T:3649    ERROR <general>:     Traceback (most recent call last):
2021-08-22 16:07:03.267 T:3649    ERROR <general>:       File "/home/osmc/.kodi/addons/script.plex/lib/player.py", line 745, in _playVideo
2021-08-22 16:07:03.267 T:3649    ERROR <general>:         self.playerObject = self.playerObject.getServerDecision()2021-08-22 16:07:03.267 T:3649    ERROR <general>:       File "/home/osmc/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexplayer.py", line 201, in getServerDecision
2021-08-22 16:07:03.267 T:3649    ERROR <general>:         decisionPath = self.getDecisionPath(directPlay)
2021-08-22 16:07:03.268 T:3649    ERROR <general>:       File "/home/osmc/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexplayer.py", line 238, in getDecisionPath
2021-08-22 16:07:03.268 T:3649    ERROR <general>:         decisionPath = self.buildTranscode(server, util.AttributeDict(), self.metadata.partIndex, True, False).decisionPath
2021-08-22 16:07:03.268 T:3649    ERROR <general>:       File "/home/osmc/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexplayer.py", line 457, in buildTranscode
2021-08-22 16:07:03.268 T:3649    ERROR <general>:         seekOffset >= obj.startOffset and seekOffset <= obj.get('startOffset', 0) + int(part.duration.asInt() / 1000)
2021-08-22 16:07:03.268 T:3649    ERROR <general>:     TypeError: '>=' not supported between instances of 'int' and 'NoneType'
2021-08-22 16:07:03.268 T:3649    ERROR <general>: _________________________________________________________________________________
```

**Comment by MagicSG1** [comment]
Also seeing this error after updating to newest build.
