### ISSUE TITLE
Plex server connection/login error

### ISSUE THREAD

**Issue by drdani42** [pannal/plex-for-kodi#27]
Hi, I recently migrated to Kodi 19.3. from 18.9. on Raspbian (after updating this from buster to bullseye). Everything is working well, except for the Plex Addon. Initial linking worked fine and I get to chose my user and then it "crashes", see log below.
No connection to the server is made, I have no access to my media.
Using a "fresh" .kodi path does not resolve it.
Any help is appreciated!

Cheers,
daniel

```
2022-01-11 18:04:41.463 T:12528   ERROR <general>: Exception in thread 
2022-01-11 18:04:41.463 T:12528   ERROR <general>: HTTP-ASYNC:https://plex.tv/users/sign_in.xml?X-Plex-Token=<removed by me>
2022-01-11 18:04:41.463 T:12528   ERROR <general>: :
                                                   
2022-01-11 18:04:41.463 T:12528   ERROR <general>: Traceback (most recent call last):
                                                   
2022-01-11 18:04:41.463 T:12528   ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
                                                   
2022-01-11 18:04:41.465 T:12528   ERROR <general>:     
2022-01-11 18:04:41.465 T:12528   ERROR <general>: self.run()
2022-01-11 18:04:41.465 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:41.465 T:12528   ERROR <general>:   File "/usr/lib/python3.9/threading.py", line 892, in run
                                                   
2022-01-11 18:04:41.467 T:12528   ERROR <general>:     
2022-01-11 18:04:41.467 T:12528   ERROR <general>: self._target(*self._args, **self._kwargs)
2022-01-11 18:04:41.467 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:41.467 T:12528   ERROR <general>:   File "/home/pi/.kodi/addons/script.plex/lib/_included_packages/plexnet/http.py", line 120, in _startAsync
                                                   
2022-01-11 18:04:41.468 T:12528   ERROR <general>:     
2022-01-11 18:04:41.468 T:12528   ERROR <general>: self.onResponse(res, context)
2022-01-11 18:04:41.468 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:41.468 T:12528   ERROR <general>:   File "/home/pi/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexrequest.py", line 46, in onResponse
                                                   
2022-01-11 18:04:41.468 T:12528   ERROR <general>:     
2022-01-11 18:04:41.469 T:12528   ERROR <general>: context['completionCallback'](self, result, context)
2022-01-11 18:04:41.469 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:41.469 T:12528   ERROR <general>:   File "/home/pi/.kodi/addons/script.plex/lib/_included_packages/plexnet/callback.py", line 37, in __call__
                                                   
2022-01-11 18:04:41.469 T:12528   ERROR <general>:     
2022-01-11 18:04:41.469 T:12528   ERROR <general>: self.func(*args, **kwargs)
2022-01-11 18:04:41.469 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:41.469 T:12528   ERROR <general>:   File "/home/pi/.kodi/addons/script.plex/lib/_included_packages/plexnet/myplexaccount.py", line 168, in onAccountResponse
                                                   
2022-01-11 18:04:41.470 T:12528   ERROR <general>:     
2022-01-11 18:04:41.470 T:12528   ERROR <general>: plexapp.refreshResources()
2022-01-11 18:04:41.470 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:41.470 T:12528   ERROR <general>:   File "/home/pi/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexapp.py", line 394, in refreshResources
                                                   
2022-01-11 18:04:41.471 T:12528   ERROR <general>:     
2022-01-11 18:04:41.471 T:12528   ERROR <general>: gdm.DISCOVERY.discover()
2022-01-11 18:04:41.471 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:41.472 T:12528   ERROR <general>:   File "/home/pi/.kodi/addons/script.plex/lib/_included_packages/plexnet/gdm.py", line 125, in discover
                                                   
2022-01-11 18:04:41.472 T:12528   ERROR <general>:     
2022-01-11 18:04:41.472 T:12528   ERROR <general>: if not util.INTERFACE.getPreference("gdm_discovery", True) or self.isActive():
2022-01-11 18:04:41.472 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:41.472 T:12528   ERROR <general>:   File "/home/pi/.kodi/addons/script.plex/lib/_included_packages/plexnet/gdm.py", line 29, in isActive
                                                   
2022-01-11 18:04:41.473 T:12528   ERROR <general>:     
2022-01-11 18:04:41.473 T:12528   ERROR <general>: return util.INTERFACE.getPreference("gdm_discovery", True) and self.thread and self.thread.isAlive()
2022-01-11 18:04:41.473 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:41.473 T:12528   ERROR <general>: AttributeError
2022-01-11 18:04:41.473 T:12528   ERROR <general>: : 
2022-01-11 18:04:41.473 T:12528   ERROR <general>: 'Thread' object has no attribute 'isAlive'
2022-01-11 18:04:41.473 T:12528   ERROR <general>: 
                                                   
2022-01-11 18:04:55.850 T:11840 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-01-11 18:04:56.118 T:11778    INFO <general>: Loading skin file: /home/pi/.kodi/addons/script.plex/resources/skins/Main/1080i/script-plex-home.xml, load type: LOAD_ON_GUI_INIT
2022-01-11 18:04:56.318 T:11778    INFO <general>: Loading skin file: /home/pi/.kodi/addons/script.plex/resources/skins/Main/1080i/script-plex-busy.xml, load type: LOAD_ON_GUI_INIT
2022-01-11 18:04:56.365 T:12506   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'KillableThread' object has no attribute 'isAlive'
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/script.plex/lib/windows/kodigui.py", line 105, in onInit
                                                       self.onFirstInit()
                                                     File "/home/pi/.kodi/addons/script.plex/lib/windows/home.py", line 358, in onFirstInit
                                                       if self.serverRefresh():
                                                     File "/home/pi/.kodi/addons/script.plex/lib/windows/busy.py", line 20, in inner
                                                       return func(*args, **kwargs)
                                                     File "/home/pi/.kodi/addons/script.plex/lib/windows/home.py", line 583, in serverRefresh
                                                       backgroundthread.BGThreader.reset()
                                                     File "/home/pi/.kodi/addons/script.plex/lib/backgroundthread.py", line 225, in reset
                                                       if self.threader._queue.empty() and not self.threader.hasTask():
                                                     File "/home/pi/.kodi/addons/script.plex/lib/backgroundthread.py", line 198, in hasTask
                                                       return any([w.working() for w in self.workers])
                                                     File "/home/pi/.kodi/addons/script.plex/lib/backgroundthread.py", line 198, in <listcomp>
                                                       return any([w.working() for w in self.workers])
                                                     File "/home/pi/.kodi/addons/script.plex/lib/backgroundthread.py", line 135, in working
                                                       return self._thread and self._thread.isAlive()
                                                   AttributeError: 'KillableThread' object has no attribute 'isAlive'
                                                   -->End of Python script error report<--
                                                   
2022-01-11 18:05:01.282 T:11778    INFO <general>: Loading skin file: /home/pi/.kodi/addons/script.plex/resources/skins/Main/1080i/script-plex-options_dialog.xml, load type: LOAD_ON_GUI_INIT
2022-01-11 18:05:01.292 T:11778   ERROR <general>: Control 1001 in window 13001 has been asked to focus, but it can't
2022-01-11 18:05:07.667 T:11778    INFO <general>: Loading skin file: /home/pi/.kodi/addons/script.plex/resources/skins/Main/1080i/script-plex-options_dialog.xml, load type: LOAD_ON_GUI_INIT
2022-01-11 18:05:07.673 T:11778   ERROR <general>: Control 1001 in window 13001 has been asked to focus, but it can't
2022-01-11 18:05:09.833 T:12506   ERROR <general>: _________________________________________________________________________________
2022-01-11 18:05:09.833 T:12506   ERROR <general>: script.plex: ERROR: 
2022-01-11 18:05:09.833 T:12506   ERROR <general>:     Traceback (most recent call last):
2022-01-11 18:05:09.833 T:12506   ERROR <general>:       File "/home/pi/.kodi/addons/script.plex/lib/main.py", line 134, in _main
2022-01-11 18:05:09.834 T:12506   ERROR <general>:         windowutils.shutdownHome()
2022-01-11 18:05:09.834 T:12506   ERROR <general>:       File "/home/pi/.kodi/addons/script.plex/lib/windows/windowutils.py", line 78, in shutdownHome
2022-01-11 18:05:09.834 T:12506   ERROR <general>:         HOME.shutdown()
2022-01-11 18:05:09.834 T:12506   ERROR <general>:       File "/home/pi/.kodi/addons/script.plex/lib/windows/home.py", line 440, in shutdown
2022-01-11 18:05:09.835 T:12506   ERROR <general>:         self.unhookSignals()
2022-01-11 18:05:09.835 T:12506   ERROR <general>:       File "/home/pi/.kodi/addons/script.plex/lib/windows/home.py", line 421, in unhookSignals
2022-01-11 18:05:09.835 T:12506   ERROR <general>:         plexapp.util.APP.off('change:selectedServer', self.onSelectedServerChange)
2022-01-11 18:05:09.835 T:12506   ERROR <general>:       File "/home/pi/.kodi/addons/script.plex/lib/_included_packages/plexnet/signalsmixin.py", line 32, in off
2022-01-11 18:05:09.835 T:12506   ERROR <general>:         self._signals[signalName].disconnect(callback)
2022-01-11 18:05:09.835 T:12506   ERROR <general>:     KeyError: 'change:selectedServer'
2022-01-11 18:05:09.835 T:12506   ERROR <general>: _________________________________________________________________________________
2022-01-11 18:05:09.836 T:12506   ERROR <general>: `
2022-01-11 18:05:09.907 T:12506   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'KillableThread' object has no attribute 'isAlive'
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/script.plex/lib/windows/kodigui.py", line 105, in onInit
                                                       self.onFirstInit()
                                                     File "/home/pi/.kodi/addons/script.plex/lib/windows/background.py", line 23, in onFirstInit
                                                       self.function()
                                                     File "/home/pi/.kodi/addons/script.plex/lib/main.py", line 148, in _main
                                                       backgroundthread.BGThreader.shutdown()
                                                     File "/home/pi/.kodi/addons/script.plex/lib/backgroundthread.py", line 233, in shutdown
                                                       self.threader.shutdown()
                                                     File "/home/pi/.kodi/addons/script.plex/lib/backgroundthread.py", line 163, in shutdown
                                                       w.shutdown()
                                                     File "/home/pi/.kodi/addons/script.plex/lib/backgroundthread.py", line 129, in shutdown
                                                       if self._thread and self._thread.isAlive():
                                                   AttributeError: 'KillableThread' object has no attribute 'isAlive'
                                                   -->End of Python script error report<--
                                                   
2022-01-11 18:05:10.865 T:11840 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-01-11 18:05:15.027 T:12506    INFO <general>: CPythonInvoker(19, /home/pi/.kodi/addons/script.plex/default.py): script successfully run
2022-01-11 18:05:15.058 T:12506    INFO <general>: Main: script.plex: REALLY FINISHED
2022-01-11 18:05:15.185 T:12506    INFO <general>: Python interpreter stopped
c2022-01-11 18:05:25.881 T:118
```

**Comment by pannal** [comment]
Which version are you using? The isAlive stuff has been fixed mid-2021.

**Comment by drdani42** [comment]
2:19.3-1~bullseye
This is the latest version available for Raspberry OS Bullseye...

**Comment by drdani42** [comment]
Oh sorry, that was the Kodi version.

The script.plex has the latest entry of [- 0.2.3 -] in the Changelog.

And this is the top from the addon.xml:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="script.plex"
       name="Plex"
       version="0.3.4"
       provider-name="Plex">
    <requires>
        <import addon="xbmc.python" version="3.0.0"/>
        <import addon="script.module.requests" version="2.22.0+matrix.1"/>
        <import addon="script.module.six" version="1.14.0+matrix.1"/>
        <import addon="script.module.kodi-six" version="0.1.3.1" />
    </requires>

Hope that helps, or let me know, how to get the version number, if 0.3.4 is not what you need.

**Comment by pannal** [comment]
You're on the wrong github then. This is my fork, not the official addon you're using.

This behavior is fixed in my fork (develop kodi19) btw.

**Comment by drdani42** [comment]
Ah, I see. Sorry!
Thank you for the very fast responses!
d
