### ISSUE TITLE
Media ends prematurely

### ISSUE THREAD

**Issue by kwilsonmg** [pannal/plex-for-kodi#40]
TV show episodes prematurely end and skip to the "next episode" screen despite there being many minutes (sometimes 50%+) remaining. This happens on an extremely frequent basis and without user interaction.

Nothing has changed in my setup nor have software updates been done to the Plex server and this issue just recently developed.

**Comment by pannal** [comment]
Interesting. Please post Kodi/PM4K DEBUG logs.

**Comment by pannal** [comment]
Wait, do you have auto-skip-credits enabled? If so, does the same (or similar behaviour) happen in an official client, such as Plex on Android?

**Comment by Wag16** [comment]
Had a similar problem with one of my movie extras. Had changed file with same name but was a longer video. All I needed to do was update metadata for the movie on the server and file played correctly after clearing cache on client.

**Comment by kwilsonmg** [comment]
Apologies for the delay -- the issue appears to be somewhat sporadic but also isolated to this Kodi Plex app. Sometimes it works fine, others it doesn't. The Kodi.log file is nearly a million lines long (over 982,000) since yesterday and most of them are the Plex app running into this chain of events.

`2023-04-09 23:08:27.278 T:14504   error <general>: script.plex: ERROR: 
2023-04-09 23:08:27.278 T:14504   error <general>:     Traceback (most recent call last):
2023-04-09 23:08:27.278 T:14504   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/util.py", line 500, in _tick
2023-04-09 23:08:27.278 T:14504   error <general>:         r.tick()
2023-04-09 23:08:27.278 T:14504   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/windows/home.py", line 436, in tick
2023-04-09 23:08:27.279 T:14504   error <general>:         self.showHubs(self.lastSection, update=True)
2023-04-09 23:08:27.279 T:14504   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/windows/home.py", line 809, in showHubs
2023-04-09 23:08:27.279 T:14504   error <general>:         self._showHubs(section=section, update=update)
2023-04-09 23:08:27.279 T:14504   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/windows/home.py", line 817, in _showHubs
2023-04-09 23:08:27.279 T:14504   error <general>:         if not plexapp.SERVERMANAGER.selectedServer.hasHubs():
2023-04-09 23:08:27.279 T:14504   error <general>:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-04-09 23:08:27.279 T:14504   error <general>:     AttributeError: 'NoneType' object has no attribute 'hasHubs'
2023-04-09 23:08:27.280 T:14504   error <general>: ______________________________________________________________`

I think that this might also be of use:
`2023-04-10 13:39:55.971 T:31798    info <general>: script.plex: BGThreader (queue.0:worker.0): Idle
2023-04-10 13:39:56.148 T:31800    info <general>: script.plex: BGThreader (queue.0:worker.3): Idle
2023-04-10 13:39:56.153 T:31804    info <general>: script.plex: BGThreader (queue.0:worker.7): Idle
2023-04-10 13:39:56.314 T:31802    info <general>: script.plex: BGThreader (queue.0:worker.5): Idle
2023-04-10 13:39:56.315 T:31799    info <general>: script.plex: BGThreader (queue.0:worker.2): Idle
2023-04-10 13:39:56.315 T:31801    info <general>: script.plex: BGThreader (queue.0:worker.4): Idle
2023-04-10 13:39:57.144 T:31803    info <general>: script.plex: BGThreader (queue.0:worker.6): Idle
2023-04-10 13:39:57.184 T:14500    info <general>: script.plex: Re-focusing 401
2023-04-10 13:39:59.273 T:31787   error <general>: _________________________________________________________________________________
2023-04-10 13:39:59.274 T:31787   error <general>: script.plex: ERROR: 
2023-04-10 13:39:59.274 T:31787   error <general>:     Traceback (most recent call last):
2023-04-10 13:39:59.275 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
2023-04-10 13:39:59.275 T:31787   error <general>:         httplib_response = self._make_request(
2023-04-10 13:39:59.275 T:31787   error <general>:                            ^^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.275 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 449, in _make_request
2023-04-10 13:39:59.275 T:31787   error <general>:         six.raise_from(e, None)
2023-04-10 13:39:59.275 T:31787   error <general>:       File "<string>", line 3, in raise_from
2023-04-10 13:39:59.276 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 444, in _make_request
2023-04-10 13:39:59.276 T:31787   error <general>:         httplib_response = conn.getresponse()
2023-04-10 13:39:59.276 T:31787   error <general>:                            ^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.276 T:31787   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1374, in getresponse
2023-04-10 13:39:59.276 T:31787   error <general>:         response.begin()
2023-04-10 13:39:59.276 T:31787   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 318, in begin
2023-04-10 13:39:59.276 T:31787   error <general>:         version, status, reason = self._read_status()
2023-04-10 13:39:59.276 T:31787   error <general>:                                   ^^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.277 T:31787   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 287, in _read_status
2023-04-10 13:39:59.277 T:31787   error <general>:         raise RemoteDisconnected("Remote end closed connection without"
2023-04-10 13:39:59.277 T:31787   error <general>:     http.client.RemoteDisconnected: Remote end closed connection without response
2023-04-10 13:39:59.277 T:31787   error <general>:     
2023-04-10 13:39:59.277 T:31787   error <general>:     During handling of the above exception, another exception occurred:
2023-04-10 13:39:59.277 T:31787   error <general>:     
2023-04-10 13:39:59.277 T:31787   error <general>:     Traceback (most recent call last):
2023-04-10 13:39:59.277 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 440, in send
2023-04-10 13:39:59.278 T:31787   error <general>:         resp = conn.urlopen(
2023-04-10 13:39:59.278 T:31787   error <general>:                ^^^^^^^^^^^^^
2023-04-10 13:39:59.278 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 787, in urlopen
2023-04-10 13:39:59.278 T:31787   error <general>:         retries = retries.increment(
2023-04-10 13:39:59.278 T:31787   error <general>:                   ^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.278 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 550, in increment
2023-04-10 13:39:59.278 T:31787   error <general>:         raise six.reraise(type(error), error, _stacktrace)
2023-04-10 13:39:59.278 T:31787   error <general>:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.278 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/packages/six.py", line 769, in reraise
2023-04-10 13:39:59.279 T:31787   error <general>:         raise value.with_traceback(tb)
2023-04-10 13:39:59.279 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
2023-04-10 13:39:59.279 T:31787   error <general>:         httplib_response = self._make_request(
2023-04-10 13:39:59.279 T:31787   error <general>:                            ^^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.279 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 449, in _make_request
2023-04-10 13:39:59.279 T:31787   error <general>:         six.raise_from(e, None)
2023-04-10 13:39:59.279 T:31787   error <general>:       File "<string>", line 3, in raise_from
2023-04-10 13:39:59.279 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 444, in _make_request
2023-04-10 13:39:59.279 T:31787   error <general>:         httplib_response = conn.getresponse()
2023-04-10 13:39:59.279 T:31787   error <general>:                            ^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.280 T:31787   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1374, in getresponse
2023-04-10 13:39:59.280 T:31787   error <general>:         response.begin()
2023-04-10 13:39:59.280 T:31787   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 318, in begin
2023-04-10 13:39:59.280 T:31787   error <general>:         version, status, reason = self._read_status()
2023-04-10 13:39:59.280 T:31787   error <general>:                                   ^^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.280 T:31787   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 287, in _read_status
2023-04-10 13:39:59.280 T:31787   error <general>:         raise RemoteDisconnected("Remote end closed connection without"
2023-04-10 13:39:59.280 T:31787   error <general>:     urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-04-10 13:39:59.280 T:31787   error <general>:     
2023-04-10 13:39:59.280 T:31787   error <general>:     During handling of the above exception, another exception occurred:
2023-04-10 13:39:59.281 T:31787   error <general>:     
2023-04-10 13:39:59.281 T:31787   error <general>:     Traceback (most recent call last):
2023-04-10 13:39:59.281 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/plexserver.py", line 200, in query
2023-04-10 13:39:59.281 T:31787   error <general>:         response = method(url, **kwargs)
2023-04-10 13:39:59.281 T:31787   error <general>:                    ^^^^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.281 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in get
2023-04-10 13:39:59.281 T:31787   error <general>:         return self.request('GET', url, **kwargs)
2023-04-10 13:39:59.281 T:31787   error <general>:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.281 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 529, in request
2023-04-10 13:39:59.282 T:31787   error <general>:         resp = self.send(prep, **send_kwargs)
2023-04-10 13:39:59.282 T:31787   error <general>:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.282 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 645, in send
2023-04-10 13:39:59.282 T:31787   error <general>:         r = adapter.send(request, **kwargs)
2023-04-10 13:39:59.282 T:31787   error <general>:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-04-10 13:39:59.282 T:31787   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 501, in send
2023-04-10 13:39:59.282 T:31787   error <general>:         raise ConnectionError(err, request=request)
2023-04-10 13:39:59.282 T:31787   error <general>:     requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-04-10 13:39:59.282 T:31787   error <general>: `

Watching this from the Plex server itself as this chain of events happens will generally yield that the Kodi Plex app just stops requesting media and then 5 or so seconds later will fail and kick you back as if you had just finished it (and queue the next episode).

**Comment by pannal** [comment]
Please add the full log files (or at least the filtered ones, but as an attachment). This quoting style is hardly readable.

Looks to me as if the Kodi app has issues connecting to the server as it tries to ping it with the current scrub status while playing. Seems like a network issue at first glance.

**Comment by kwilsonmg** [comment]
Just odd as it doesn't have any issues normally. The issue seems to have resolved itself once again on its own inexplicably.
