### ISSUE TITLE
Addon fails to start with "List index out of range" error

### ISSUE THREAD

**Issue by DoctorOctagonapus** [pannal/plex-for-kodi#48]
Currently running LibreELEC 11.0.3 on a Pi4, addon version 0.5.3 from the Don't Panic repo.

The addon will not run at all for me. No message is displayed on the screen but this stacktrace appears in kodi.log:

```
2023-09-24 15:06:57.054 T:28824   error <general>: Control 55 in window 10001 has been asked to focus, but it can't
2023-09-24 15:06:57.756 T:8728    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.plexmod/plugin.py", line 7, in <module>
                                                       from lib import _included_packages, plex, util
                                                     File "/storage/.kodi/addons/script.plexmod/lib/plex.py", line 14, in <module>
                                                       from . import util
                                                     File "/storage/.kodi/addons/script.plexmod/lib/util.py", line 46, in <module>
                                                       CHANNELMAPPING = dict((t["value"], t["label"]) for t in getChannelMapping())
                                                                                                               ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.plexmod/lib/util.py", line 43, in getChannelMapping
                                                       return list(filter(lambda i: i["id"] == "audiooutput.channels", data))[0]["options"]
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2023-09-24 15:06:57.877 T:8727    error <general>: GetDirectory - Error getting plugin://script.plexmod/
2023-09-24 15:06:57.900 T:28824   error <general>: CGUIMediaWindow::GetDirectory(plugin://script.plexmod/) failed
```

I've tried a purging and reinstalling the addon, rebooting the device, and installing various other versions but nothing works.

**Comment by pannal** [comment]
Interesting, do you know which kodi version it's based on?
Seems like it's missing a setting that works in any normal kodi instance.

I can add a fallback, but that would mean that the AC3/DTS settings in PM4K won't really work.

BTW you should be able to go back a couple of versions for the time being, before the audio handling was added.

**Comment by DoctorOctagonapus** [comment]
Ha the one thing I forgot to list sorry about that! LibreELEC 11.0.3 runs Kodi 20.2.

**Comment by pannal** [comment]
Yeah, so, the addon gets the set up amount of audio channels by querying the kodi API for "audiooutput.channels" and in your case it fails.

Not sure if that's related to your setup or libreelec in general. One possible solution would be to fall back to simple 2 channel assumption.

**Comment by pannal** [comment]
I'll add a fallback to the next version. Can you add `DEBUG_LOG("ALL SETTINGS: %s" % rpc.Settings.GetSettings())` to the end of `lib/util.py` and post the results of the "ALL SETTINGS" log entry when starting PM4K? Thanks!

**Comment by pannal** [comment]
Is this fixed for you?

**Comment by DoctorOctagonapus** [comment]
Hi that does seem to have fixed it thanks for that. The app now loads and plays videos, and the sound device is working perfectly.
