### ISSUE TITLE
0.7.1-rev4 exception

### ISSUE THREAD

**Issue by bowlingbeeg** [pannal/plex-for-kodi#74]
## Details:
- Add-on version: 0.7.1-rev4
- Kodi version: 20.2
- OS Platform: Android
- Hardware: Zidoo Z9X

## Checklist
- [X] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

While running through the new 0.7.1-rev4 I hit this error trying to bring up the pre-play screen.  It looks like the query itself eats the error so the try/catch in plexobjects.py doesn't and then just proceeds further with data set to None.

```python
2023-12-17 10:19:25.002 T:22442    info <general>: Loading skin file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/resources/skins/Main/1080i/script-plex-pre_play.xml, load type: LOAD_ON_GUI_INIT
2023-12-17 10:19:25.229 T:23811    info <general>: script.plex: PrePlay: Showing video info: <plexnet.video.Movie object at 0x872b4f70>
2023-12-17 10:19:25.230 T:23811    info <general>: script.plex: API: GET https://192-168-10-46.cebd87c5efb1435b90876d62299d89eb.plex.direct:32400/library/metadata/26019?checkFiles=1&includeChapters=1&includeExtras=1&includeExtrasCount=10&includeMarkers=1&includeReviews=1&X-Plex-Token=****
2023-12-17 10:19:25.310 T:23811   error <general>: _________________________________________________________________________________
2023-12-17 10:19:25.310 T:23811   error <general>: script.plex: ERROR: 
2023-12-17 10:19:25.310 T:23811   error <general>:     Traceback (most recent call last):
2023-12-17 10:19:25.310 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 790, in urlopen
2023-12-17 10:19:25.310 T:23811   error <general>:         response = self._make_request(
2023-12-17 10:19:25.310 T:23811   error <general>:                    ^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.311 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 536, in _make_request
2023-12-17 10:19:25.311 T:23811   error <general>:         response = conn.getresponse()
2023-12-17 10:19:25.311 T:23811   error <general>:                    ^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.311 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 461, in getresponse
2023-12-17 10:19:25.311 T:23811   error <general>:         httplib_response = super().getresponse()
2023-12-17 10:19:25.311 T:23811   error <general>:                            ^^^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.311 T:23811   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1374, in getresponse
2023-12-17 10:19:25.311 T:23811   error <general>:         response.begin()
2023-12-17 10:19:25.311 T:23811   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 318, in begin
2023-12-17 10:19:25.311 T:23811   error <general>:         version, status, reason = self._read_status()
2023-12-17 10:19:25.311 T:23811   error <general>:                                   ^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.311 T:23811   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 287, in _read_status
2023-12-17 10:19:25.311 T:23811   error <general>:         raise RemoteDisconnected("Remote end closed connection without"
2023-12-17 10:19:25.311 T:23811   error <general>:     http.client.RemoteDisconnected: Remote end closed connection without response
2023-12-17 10:19:25.311 T:23811   error <general>:     
2023-12-17 10:19:25.312 T:23811   error <general>:     During handling of the above exception, another exception occurred:
2023-12-17 10:19:25.312 T:23811   error <general>:     
2023-12-17 10:19:25.312 T:23811   error <general>:     Traceback (most recent call last):
2023-12-17 10:19:25.312 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 486, in send
2023-12-17 10:19:25.312 T:23811   error <general>:         resp = conn.urlopen(
2023-12-17 10:19:25.312 T:23811   error <general>:                ^^^^^^^^^^^^^
2023-12-17 10:19:25.312 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 844, in urlopen
2023-12-17 10:19:25.312 T:23811   error <general>:         retries = retries.increment(
2023-12-17 10:19:25.312 T:23811   error <general>:                   ^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.312 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 470, in increment
2023-12-17 10:19:25.312 T:23811   error <general>:         raise reraise(type(error), error, _stacktrace)
2023-12-17 10:19:25.312 T:23811   error <general>:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.312 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/util.py", line 38, in reraise
2023-12-17 10:19:25.312 T:23811   error <general>:         raise value.with_traceback(tb)
2023-12-17 10:19:25.312 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 790, in urlopen
2023-12-17 10:19:25.312 T:23811   error <general>:         response = self._make_request(
2023-12-17 10:19:25.313 T:23811   error <general>:                    ^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.313 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 536, in _make_request
2023-12-17 10:19:25.313 T:23811   error <general>:         response = conn.getresponse()
2023-12-17 10:19:25.313 T:23811   error <general>:                    ^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.313 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 461, in getresponse
2023-12-17 10:19:25.313 T:23811   error <general>:         httplib_response = super().getresponse()
2023-12-17 10:19:25.313 T:23811   error <general>:                            ^^^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.313 T:23811   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1374, in getresponse
2023-12-17 10:19:25.313 T:23811   error <general>:         response.begin()
2023-12-17 10:19:25.313 T:23811   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 318, in begin
2023-12-17 10:19:25.313 T:23811   error <general>:         version, status, reason = self._read_status()
2023-12-17 10:19:25.313 T:23811   error <general>:                                   ^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.313 T:23811   error <general>:       File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 287, in _read_status
2023-12-17 10:19:25.313 T:23811   error <general>:         raise RemoteDisconnected("Remote end closed connection without"
2023-12-17 10:19:25.314 T:23811   error <general>:     urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-12-17 10:19:25.314 T:23811   error <general>:     
2023-12-17 10:19:25.314 T:23811   error <general>:     During handling of the above exception, another exception occurred:
2023-12-17 10:19:25.314 T:23811   error <general>:     
2023-12-17 10:19:25.314 T:23811   error <general>:     Traceback (most recent call last):
2023-12-17 10:19:25.314 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/plexserver.py", line 215, in query
2023-12-17 10:19:25.314 T:23811   error <general>:         response = method(url, **kwargs)
2023-12-17 10:19:25.314 T:23811   error <general>:                    ^^^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.314 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 602, in get
2023-12-17 10:19:25.314 T:23811   error <general>:         return self.request("GET", url, **kwargs)
2023-12-17 10:19:25.314 T:23811   error <general>:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.314 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
2023-12-17 10:19:25.314 T:23811   error <general>:         resp = self.send(prep, **send_kwargs)
2023-12-17 10:19:25.314 T:23811   error <general>:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.315 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 703, in send
2023-12-17 10:19:25.315 T:23811   error <general>:         r = adapter.send(request, **kwargs)
2023-12-17 10:19:25.315 T:23811   error <general>:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-17 10:19:25.315 T:23811   error <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 501, in send
2023-12-17 10:19:25.315 T:23811   error <general>:         raise ConnectionError(err, request=request)
2023-12-17 10:19:25.315 T:23811   error <general>:     requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-12-17 10:19:25.315 T:23811   error <general>: _________________________________________________________________________________
2023-12-17 10:19:25.315 T:23811   error <general>: `
2023-12-17 10:19:25.433 T:23811   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/windows/kodigui.py", line 135, in onInit
                                                       self.onFirstInit()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/windows/preplay.py", line 92, in onFirstInit
                                                       self.setup()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/windows/busy.py", line 43, in inner
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/windows/preplay.py", line 508, in setup
                                                       self.video.reload(checkFiles=1, **VIDEO_RELOAD_KW)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/video.py", line 449, in reload
                                                       Video.reload(self, *args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexmod/lib/_included_packages/plexnet/plexobjects.py", line 249, in reload
                                                       self._setData(data[0])
                                                                     ~~~~^^^
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
```

**Comment by pannal** [comment]
Should be fixed with 0.7.2
